# Generated by Django 4.2.14 on 2026-02-02 20:06

import datetime
from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def migrate_assigned_to_to_taskassignment(apps, schema_editor):
    Task = apps.get_model("core", "Task")
    TaskAssignment = apps.get_model("core", "TaskAssignment")
    for task in Task.objects.all():
        assigned_id = getattr(task, "assigned_to_id", None)
        if assigned_id:
            try:
                TaskAssignment.objects.create(task_id=task.id, assignee_id=assigned_id)
            except Exception:
                pass


def reverse_migrate_assigned_to(apps, schema_editor):
    Task = apps.get_model("core", "Task")
    TaskAssignment = apps.get_model("core", "TaskAssignment")
    for task in Task.objects.all():
        task_assignment = TaskAssignment.objects.filter(task_id=task.id).first()
        if task_assignment:
            task.assigned_to_id = task_assignment.assignee_id
            task.save(update_fields=["assigned_to_id"])


def create_tags(apps, schema_editor):
    Tag = apps.get_model("core", "Tag")
    Tag.objects.create(name="Delivery", emoji="🚀", category="phase")
    Tag.objects.create(name="Ideation", emoji="💡", category="phase")
    Tag.objects.create(name="Pitching", emoji="💬", category="phase")
    Tag.objects.create(name="Production", emoji="🛠️", category="phase")
    Tag.objects.create(name="Weekly 1-1", emoji="👥", category="task")
    Tag.objects.create(name="Administrative", emoji="💼", category="task")
    Tag.objects.create(name="Town Hall", emoji="🏛️", category="task")
    Tag.objects.create(name="Programming", emoji="🤖", category="task")
    Tag.objects.create(name="Marketing", emoji="📈", category="task")
    Tag.objects.create(name="Project Management", emoji="🏢", category="task")
    Tag.objects.create(name="Design", emoji="🎨", category="task")
    Tag.objects.create(name="Untagged", emoji="🏷️", category="system")


def reverse_tags(apps, schema_editor):
    Tag = apps.get_model("core", "Tag")
    Tag.objects.all().delete()


def create_materialized_views(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE MATERIALIZED VIEW IF NOT EXISTS core_timeentry_daily_totals AS
        SELECT
            user_id,
            DATE(start_datetime) AS day,
            SUM(duration) AS total_duration
        FROM core_timeentry
        GROUP BY user_id, DATE(start_datetime);

        CREATE UNIQUE INDEX IF NOT EXISTS idx_daily_totals_user_day
        ON core_timeentry_daily_totals (user_id, day);

        CREATE MATERIALIZED VIEW IF NOT EXISTS core_project_monthly_totals AS
        SELECT
            project_id,
            user_id,
            DATE_TRUNC('month', start_datetime)::date AS month_start,
            SUM(duration) AS total_duration
        FROM core_timeentry
        GROUP BY project_id, user_id, DATE_TRUNC('month', start_datetime)::date;

        CREATE UNIQUE INDEX IF NOT EXISTS idx_monthly_totals_project_user_month
        ON core_project_monthly_totals (project_id, user_id, month_start);
        """
    )


def drop_materialized_views(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DROP MATERIALIZED VIEW IF EXISTS core_project_monthly_totals;
        DROP MATERIALIZED VIEW IF EXISTS core_timeentry_daily_totals;
        """
    )

class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_project_monthly_threshold_hours'), ('core', '0003_timeentry_manager_comment_and_more'), ('core', '0004_comment_alter_timeentry_options_delete_clocksession_and_more'), ('core', '0005_clocksession'), ('core', '0007_taskassignment_m2m'), ('core', '0008_tag_timeentry_tags'), ('core', '0009_seed_tags'), ('core', '0010_timeentry_indexes'), ('core', '0011_user_project_hours_daily_view'), ('core', '0012_project_task_status_summary_view'), ('core', '0013_fix_daily_hours_view'), ('core', '0014_merge_20251106_0840'), ('core', '0015_user_monthly_threshold_hours'), ('core', '0016_fix_daily_hours_view_final'), ('core', '0017_create_timeentry_daily_summary'), ('core', '0018_alter_timeentrydailysummary_prefix_sum_and_more'), ('core', '0019_timeentry_query_indexes'), ('core', '0020_create_materialized_views'), ('core', '0021_activetimeentry'), ('core', '0022_delete_timeentrydailysummary'), ('core', '0023_clocksession_clocksession_user_time_idx_and_more'), ('core', '0024_dailysummary'), ('core', '0025_project_billable'), ('core', '0026_client_alter_user_role_invoice_datarequest_and_more'), ('core', '0027_datarequest_analysis_image_count_and_more'), ('core', '0028_requestfile'), ('core', '0029_client_logo')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('superuser', 'Superuser'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=20)),
                ('must_set_password', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('monthly_threshold_hours', models.DecimalField(decimal_places=2, default=0, help_text='Monthly hour limit for this project', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organizationunit')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotted_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'unique_together': {('project', 'assignee')},
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billable', models.BooleanField(default=False)),
                ('billing_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by_snapshot', models.CharField(blank=True, help_text='Snapshot of creator name for deleted users', max_length=200)),
                ('is_idle', models.BooleanField(default=False, help_text='Marked as idle time')),
                ('location', models.CharField(blank=True, help_text='Geographic location', max_length=200)),
                ('locked', models.BooleanField(default=False)),
                ('memory_source', models.CharField(blank=True, help_text='Source of automatic tracking', max_length=50)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visible_to', models.ManyToManyField(blank=True, related_name='visible_entries', to=settings.AUTH_USER_MODEL)),
                ('manager_comment', models.TextField(blank=True, help_text='Manager comment on this time entry')),
                ('manager_comment_at', models.DateTimeField(blank=True, help_text='When the manager comment was added', null=True)),
                ('manager_comment_by', models.ForeignKey(blank=True, help_text='Manager who added the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commented_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('time_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.timeentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClockSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.DateTimeField()),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clock_in_time'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotted_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
            ],
            options={
                'unique_together': {('task', 'assignee')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(related_name='task_assignments', through='core.TaskAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            code=migrate_assigned_to_to_taskassignment,
            reverse_code=reverse_migrate_assigned_to,
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(choices=[('phase', 'Phase'), ('task', 'Task'), ('system', 'System')], default='task', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='timeentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='time_entries', to='core.tag'),
        ),
        migrations.RunPython(
            code=create_tags,
            reverse_code=reverse_tags,
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS idx_time_entries_user ON core_timeentry (user_id);\nCREATE INDEX IF NOT EXISTS idx_time_entries_date ON core_timeentry (start_datetime);\nCREATE INDEX IF NOT EXISTS idx_time_entries_project ON core_timeentry (project_id);\n',
            reverse_sql='DROP INDEX IF EXISTS idx_time_entries_user;\nDROP INDEX IF EXISTS idx_time_entries_date;\nDROP INDEX IF EXISTS idx_time_entries_project;\n',
        ),
        migrations.RunSQL(
            sql='\nCREATE OR REPLACE VIEW core_user_project_hours_daily_view AS\nSELECT\n  DATE(start_datetime) AS day,\n  user_id,\n  project_id,\n  SUM(duration) AS total_duration\nFROM core_timeentry\nGROUP BY day, user_id, project_id;\n',
            reverse_sql='DROP VIEW IF EXISTS core_user_project_hours_daily_view;',
        ),
        migrations.RunSQL(
            sql="\nCREATE OR REPLACE VIEW core_project_task_status_summary_view AS\nSELECT\n  t.project_id AS project_id,\n  SUM(CASE WHEN t.status = 'todo' THEN 1 ELSE 0 END) AS todo_count,\n  SUM(CASE WHEN t.status = 'in_progress' THEN 1 ELSE 0 END) AS in_progress_count,\n  SUM(CASE WHEN t.status = 'done' THEN 1 ELSE 0 END) AS completed_count,\n  COUNT(*) AS total_tasks\nFROM core_task t\nGROUP BY t.project_id;\n",
            reverse_sql='DROP VIEW IF EXISTS core_project_task_status_summary_view;',
        ),
        migrations.RunSQL(
            sql="\nCREATE OR REPLACE VIEW core_user_project_hours_daily_view AS\nSELECT\n  DATE(start_datetime) AS day,\n  user_id,\n  project_id,\n  SUM(EXTRACT(EPOCH FROM (end_datetime - start_datetime))) * INTERVAL '1 second' AS total_duration\nFROM core_timeentry\nGROUP BY day, user_id, project_id;\n",
            reverse_sql='DROP VIEW IF EXISTS core_user_project_hours_daily_view;',
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_threshold_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly hour limit for this user', max_digits=8),
        ),
        migrations.RunSQL(
            sql='DROP VIEW IF EXISTS core_user_project_hours_daily_view CASCADE;',
        ),
        migrations.RunSQL(
            sql="\nCREATE VIEW core_user_project_hours_daily_view AS\nSELECT\n  DATE(start_datetime) AS day,\n  user_id,\n  SUM(EXTRACT(EPOCH FROM (end_datetime - start_datetime))) * INTERVAL '1 second' AS total_duration\nFROM core_timeentry\nGROUP BY day, user_id;\n",
        ),
        migrations.CreateModel(
            name='TimeEntryDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_duration', models.DurationField(default=datetime.timedelta(0), help_text='Total duration for this day')),
                ('prefix_sum', models.DurationField(default=datetime.timedelta(0), help_text='Cumulative sum up to this date for user/project/task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'project', 'task', 'date'],
                'indexes': [models.Index(fields=['user', 'project', 'date'], name='core_timeen_user_id_7657e6_idx'), models.Index(fields=['user', 'project', 'task', 'date'], name='core_timeen_user_id_418be5_idx'), models.Index(fields=['date'], name='core_timeen_date_f123c6_idx')],
                'unique_together': {('date', 'user', 'project', 'task')},
            },
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'start_datetime'], name='timeentry_user_start_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['project', 'start_datetime'], name='timeentry_project_start_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='timeentry_start_end_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['state', 'start_datetime'], name='timeentry_state_start_idx'),
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS core_timeentry_visible_to_user_idx ON core_timeentry_visible_to (user_id);\nCREATE INDEX IF NOT EXISTS core_timeentry_visible_to_entry_idx ON core_timeentry_visible_to (timeentry_id);',
            reverse_sql='DROP INDEX IF EXISTS core_timeentry_visible_to_user_idx;\nDROP INDEX IF EXISTS core_timeentry_visible_to_entry_idx;',
        ),
        migrations.RunPython(
            code=create_materialized_views,
            reverse_code=drop_materialized_views,
        ),
        migrations.CreateModel(
            name='ActiveTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_time_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.DeleteModel(
            name='TimeEntryDailySummary',
        ),
        migrations.AddIndex(
            model_name='clocksession',
            index=models.Index(fields=['user', 'clock_in_time'], name='clocksession_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='clocksession',
            index=models.Index(fields=['date'], name='clocksession_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='task_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='task_due_date_idx'),
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_duration', models.DurationField(default=datetime.timedelta(0))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='dailysummary_user_date_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='billable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(blank=True, help_text='Domain for auto-verification if permitted', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('manager', 'Manager'), ('employee', 'Employee'), ('client', 'Client')], max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoices/%Y/%m/')),
                ('billing_period', models.DateField(help_text='First day of the billing month')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.client'),
        ),
        migrations.AddField(
            model_name='user',
            name='client_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client'),
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='requests/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending_review', max_length=30)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimation_notes', models.TextField(blank=True)),
                ('estimated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('estimated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimated_requests', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', to='core.project')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_data', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_request', to='core.task')),
                ('analysis_image_count', models.IntegerField(blank=True, null=True)),
                ('analysis_outlet_count', models.IntegerField(blank=True, null=True)),
                ('auto_estimated_cost_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='requests/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.datarequest')),
            ],
        ),
    ]
