# Generated by Django 4.2.14 on 2026-05-14 05:13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification_kinds_leave_decisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date the lead was received')),
                ('name', models.CharField(max_length=200)),
                ('contact_details', models.CharField(blank=True, help_text='Phone, email, or both', max_length=255)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('email', 'Email'), ('phone', 'Phone Call'), ('website', 'Website'), ('other', 'Other')], default='other', max_length=20)),
                ('lead_type', models.CharField(choices=[('ad', 'Advertisement'), ('social_media', 'Social Media'), ('personal_reference', 'Personal Reference'), ('cold_outreach', 'Cold Outreach'), ('event', 'Event / Conference'), ('inbound', 'Inbound Inquiry'), ('other', 'Other')], default='other', max_length=30)),
                ('work_type', models.CharField(choices=[('app', 'Mobile App'), ('web', 'Web Development'), ('design', 'Design / Branding'), ('marketing', 'Marketing'), ('data', 'Data / Analytics'), ('consulting', 'Consulting'), ('other', 'Other')], default='other', max_length=20)),
                ('enquiry_video_link', models.URLField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('suggestion', models.TextField(blank=True)),
                ('reason_not_proceed', models.TextField(blank=True)),
                ('last_followed_up', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_discussion', 'In Discussion'), ('ongoing', 'Ongoing'), ('converted', 'Converted'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('status_description', models.TextField(blank=True, help_text='Detailed notes about the current status')),
                ('invoice_status', models.CharField(choices=[('none', 'Not Generated'), ('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='none', max_length=20)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_notes', models.TextField(blank=True)),
                ('invoice_file_url', models.URLField(blank=True, help_text='Optional link to an uploaded invoice file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='lead_status_idx'), models.Index(fields=['date'], name='lead_date_idx')],
            },
        ),
    ]
