# Generated by Django 4.2.14 on 2026-05-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lead_client_lead_client_admin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_reminder_sent_for',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_reminder_sent_for',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('request_submitted', 'Data Request Submitted'), ('leave_submitted', 'Leave Request Submitted'), ('leave_approved', 'Leave Request Approved'), ('leave_rejected', 'Leave Request Rejected'), ('task_assigned', 'Task Assigned'), ('task_start_today', 'Task Starts Today'), ('task_due_today', 'Task Due Today'), ('extension_submitted', 'Extension Request Submitted'), ('extension_approved', 'Extension Request Approved'), ('extension_rejected', 'Extension Request Rejected')], max_length=50),
        ),
    ]
