# Generated by Django 4.2.14 on 2026-05-14 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_taskextensionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('aws', 'AWS'), ('cdn', 'CDN'), ('database', 'Database'), ('ftp', 'FTP / SSH'), ('smtp', 'SMTP / Email'), ('dlt', 'DLT'), ('api_key', 'API Key'), ('other', 'Other')], default='other', max_length=20)),
                ('kind_custom', models.CharField(blank=True, max_length=80)),
                ('label', models.CharField(help_text="Human-readable name e.g. 'Production AWS'", max_length=200)),
                ('username', models.CharField(blank=True, help_text='Username, email, account ID, etc.', max_length=255)),
                ('secret', models.TextField(blank=True, help_text='Password, API key, or token')),
                ('url', models.URLField(blank=True, help_text='Login URL or dashboard')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credentials', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'kind'], name='cred_project_kind_idx')],
            },
        ),
    ]
