# Generated by Django 4.2.14 on 2026-05-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('request_submitted', 'Data Request Submitted'), ('leave_submitted', 'Leave Request Submitted'), ('leave_approved', 'Leave Request Approved'), ('leave_rejected', 'Leave Request Rejected'), ('salary_processed', 'Salary Processed — Approval Needed'), ('salary_acknowledged', 'Salary Receipt Acknowledged'), ('task_assigned', 'Task Assigned'), ('task_start_today', 'Task Starts Today'), ('task_due_today', 'Task Due Today'), ('extension_submitted', 'Extension Request Submitted'), ('extension_approved', 'Extension Request Approved'), ('extension_rejected', 'Extension Request Rejected')], max_length=50),
        ),
    ]
