# Generated by Django 4.2.14 on 2026-05-18 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


BUILTIN_TYPES = [
    ("internal", "Server Cost", False),
    ("internal", "CDN Cost", False),
    ("internal", "API Cost", False),
    ("external", "Food", False),
    ("external", "Meeting", False),
    ("external", "External Employee", True),
]


def seed_expense_types(apps, schema_editor):
    ExpenseType = apps.get_model("core", "ExpenseType")
    for scope, name, requires_person in BUILTIN_TYPES:
        ExpenseType.objects.get_or_create(
            scope=scope, name=name,
            defaults={"is_builtin": True, "requires_person": requires_person},
        )


def unseed_expense_types(apps, schema_editor):
    ExpenseType = apps.get_model("core", "ExpenseType")
    for scope, name, _ in BUILTIN_TYPES:
        ExpenseType.objects.filter(scope=scope, name=name, is_builtin=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_salarypayment_salary_cut'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('is_builtin', models.BooleanField(default=False)),
                ('requires_person', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_types_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scope', 'name'],
                'unique_together': {('scope', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('person_name', models.CharField(blank=True, max_length=120)),
                ('person_role', models.CharField(blank=True, max_length=120)),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.expensetype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_expenses', to='core.project')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_expense', to='core.transaction')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['project', 'scope'], name='fin_pexp_proj_scope_idx')],
            },
        ),
        migrations.RunPython(seed_expense_types, unseed_expense_types),
    ]
