# Generated by Django 4.2.14 on 2026-05-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_expensetype_projectexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='attachment',
            field=models.FileField(blank=True, upload_to='offer_letters/%Y/%m/%d/'),
        ),
    ]
