# Generated by Django 4.2.14 on 2026-05-18 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_offerletter_content_alter_offerletter_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='done',
            field=models.BooleanField(blank=True, default=None, help_text='Per-hour completion: true=done, false=not done, null=unmarked', null=True),
        ),
        migrations.CreateModel(
            name='DailyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plan_items', to='core.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plan_items', to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plan_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='timeentry',
            name='plan_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='core.dailyplanitem'),
        ),
        migrations.AddIndex(
            model_name='dailyplanitem',
            index=models.Index(fields=['user', 'plan_date'], name='dailyplan_user_date_idx'),
        ),
    ]
