# Generated by Django 4.2.14 on 2026-05-19 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_timeentry_done_dailyplanitem_timeentry_plan_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='INR', max_length=8),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_marked_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('requested', 'Payment Requested'), ('paid', 'Marked Paid by Client'), ('completed', 'Payment Completed')], default='requested', max_length=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='core.transaction'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_period',
            field=models.DateField(blank=True, help_text='First day of the billing month', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('request_submitted', 'Data Request Submitted'), ('leave_submitted', 'Leave Request Submitted'), ('leave_approved', 'Leave Request Approved'), ('leave_rejected', 'Leave Request Rejected'), ('salary_processed', 'Salary Processed — Approval Needed'), ('salary_acknowledged', 'Salary Receipt Acknowledged'), ('task_assigned', 'Task Assigned'), ('task_start_today', 'Task Starts Today'), ('task_due_today', 'Task Due Today'), ('extension_submitted', 'Extension Request Submitted'), ('extension_approved', 'Extension Request Approved'), ('extension_rejected', 'Extension Request Rejected'), ('invoice_issued', 'Invoice Issued — Payment Requested'), ('invoice_paid', 'Invoice Marked Paid by Client'), ('invoice_completed', 'Invoice Payment Completed')], max_length=50),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
